VAGRANTFILE_API_VERSION = "2"
MINIONS = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
  end

  config.vm.define :saltmaster do |master_config|
    master_config.vm.box = "ubuntu/xenial64"
    master_config.vm.host_name = 'saltmaster'
    master_config.vm.network "private_network", ip: "192.168.50.10"
    master_config.vm.provision :shell, path: "bootstrap.sh", :args => "saltmaster #{MINIONS}"
  end


  (1..MINIONS).each do |i|
  	config.vm.define "saltminion#{i}" do |minion_config|
    	minion_config.vm.box = "ubuntu/xenial64"
    	minion_config.vm.host_name = "saltminion#{i}"
    	minion_config.vm.network "private_network", ip: "192.168.50.1#{i}"
    	minion_config.vm.provision :shell, path: "bootstrap.sh", :args => "saltminion#{i} #{MINIONS}"
  	end

  end

end
